### ISSUE TITLE
Deck Descriptions Use Dark Fonts

### ISSUE THREAD

**Issue by oooooooooooooooo** [my-Anki/Beautify-Anki#29]
Hi, I'm not sure if this has been reported already. I saw someone already noted that the pie chart text is a dark gray instead of a more visible light color so I don't need to repeat that but it's also visible in my screenshots.

![Screenshot (111)](https://user-images.githubusercontent.com/8386495/87884437-8cdf0380-ca0e-11ea-88be-8806d0008f25.png)
![Screenshot (112)](https://user-images.githubusercontent.com/8386495/87884444-910b2100-ca0e-11ea-99cf-bacf3a065475.png)

**Comment by achen898** [comment]
This also happens when you finish a deck but there are still some cards remaining due to the interval not having been met yet. My background is light so it doesn't affect me as much but it's hard to see on a darker background.
![image](https://user-images.githubusercontent.com/64118247/88843020-4b302480-d195-11ea-89b9-0bca3ddffcec.png)

**Comment by ShoroukAziz** [comment]
Thanks for reporting!
will be fixed next update
